FROM python:3.14-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

# Instalacja zależności
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev

COPY frontend.py ./

CMD ["uv", "run", "streamlit", "run", "frontend.py", "--server.port", "8501", "--server.address", "0.0.0.0"]