notice_types = {
    "ContractNotice": "Ogłoszenie o zamówieniu",
    "AgreementIntentionNotice": "Ogłoszenie o zamiarze zawarcia umowy",
    "TenderResultNotice": "Ogłoszenie o wyniku postępowania",
    "CompetitionNotice": "Ogłoszenie o konkursie",
    "CompetitionResultNotice": "Ogłoszenie o wynikach konkursu",
    "NoticeUpdateNotice": "Ogłoszenie o zmianie ogłoszenia",
    "AgreementUpdateNotice": "Ogłoszenie o zmianie umowy",
    "ContractPerformingNotice": "Ogłoszenie o wykonaniu umowy",
    "CircumstancesFulfillmentNotice": "Ogłoszenie o spełnianiu okoliczności, o których mowa w art. 214 ust.1 pkt 11-14 ustawy",
    "SmallContractNotice": "Ogłoszenie dotyczące zamówienia, dla którego nie ma obowiązku stosowania ustawy Pzp",
    "ConcessionNotice": "Ogłoszenie o koncesji",
    "ConcessionIntentionAgreementNotice": "Ogłoszenie o zamiarze zawarcia umowy koncesji",
    "NoticeUpdateConcession": "Ogłoszenie o zmianie ogłoszenie dot. koncesji",
    "ConcessionAgreementNotice": "Ogłoszenie o zawarciu umowy koncesji",
    "ConcessionUpdateAgreementNotice": "Ogłoszenie o zmianie umowy koncesji",
}

response_attributes = {
    "objectId": "Identyfikator ogłoszenia",
    "clientType": "Rodzaj zamawiającego",
    "TenderType": "Tryb zamówienia",
    "noticeType": "Rodzaj ogłoszenia",
    "noticeNumber": "Numer ogłoszenia",
    "bzpNumber": "Numer BZP",
    "isTenderAmountBelowEU": "Czy procedura nieunijna",
    "publicationDate": "Data publikacji",
    "orderObject": "Nazwa zamówienia / nazwa konkursu",
    "cpvCode": "Kod CPV",
    "submittingOffersDate": "Termin składania ofert",
    "procedureResult": "Wynik postępowania",
    "organizationName": "Nazwa zamawiającego",
    "organizationCity": "Miejscowość zamawiającego",
    "organizationProvince": "Województwo zamawiającego",
    "organizationCountry": "Kraj zamawiającego",
    "organizationNationalId": "Krajowy numer identyfikacyjny",
    "organizationId": "Id organizacji",
    "tenderId": "Identyfikator postępowania",
    "htmlBody": "Zawartość ogłoszenia w postaci HTML",
    "contractorName": "Nazwa wykonawcy",
    "contractorCity": "Miejscowość wykonawcy",
    "contractorProvince": "Województwo wykonawcy",
    "contractorCountry": "Kraj wykonawcy",
    "contractorNationalId": "Krajowy numer identyfikacyjny",
}
