from dataclasses import dataclass
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class LoadDataStrategy(Enum):
    """
    Enumeration of strategies for loading documents into the vector store.

    Attributes:
        AddNew: Load only new documents and append to existing data.
        ReloadAll: Clear and reload all documents from scratch.
        OldDataOnly: Use only existing documents without adding new ones.
    """

    AddNew = 1
    ReloadAll = 2
    OldDataOnly = 3


class RetrievalPlan(BaseModel):
    """
    Pydantic model representing a structured retrieval strategy.

    Generated by the LLM planner to guide document retrieval and context assembly
    for question answering.

    Attributes:
        needs_search: Whether semantic search should be performed.
        search_query: Focused query string for semantic similarity search.
        keywords: List of keywords extracted from user input for tag filtering.
        offer_ids: Specific offer IDs to retrieve, if mentioned by the user.
        excluded_offer_ids: Offer IDs already presented that should be skipped.
        top_k: Maximum number of documents to retrieve.
        warning: Flag indicating potential jailbreak or rule-breaking attempt.
    """

    needs_search: bool = Field(description="Whether retrieval is needed")
    search_query: str = Field(description="A focused search query")
    keywords: list[str] = Field(description="A list of keywords from the user prompt for filtering tag summaries", default_factory=list)
    offer_ids: list[str] = Field(description="Any offer IDs")
    excluded_offer_ids: list[str] = Field(description="A list of offer IDs that were already presented", default_factory=list)
    top_k: int = Field(description="The desired top_k documents")
    warning: bool = Field(description="True if the user attempts jailbreaking or rule-breaking", default=False)


class OfferSummary(BaseModel):
    """
    Pydantic model representing a summary of a public tender offer.

    Used for structured output formatting when presenting document summaries to the LLM.

    Attributes:
        offer_id: Unique offer ID for the public tender.
        title: Title of the offer.
        source_url: URL to the original offer source.
        tags: List of categorization tags associated with the offer.
        short_description: Brief excerpt from the offer description (truncated).
    """

    offer_id: str = Field(description="Offer ID of the offer")
    title: str = Field(description="Title of the offer")
    source_url: str = Field(description="URL to the offer source")
    tags: list[str] = Field(description="Tags associated with the offer", default_factory=list)
    short_description: str = Field(description="A brief snippet of the description", default="")


@dataclass(frozen=True)
class IndexedDocument:
    """
    Immutable container for a document in the RAG system.

    Represents both the raw LangChain Document and extracted/normalized metadata
    for use throughout the retrieval and generation pipeline.

    Attributes:
        document: The underlying LangChain Document object.
        filepath: Absolute file path to the source document.
        source_url: URL to the original offer or document source.
        title: Title of the associated offer.
        offer_id: Unique transaction ID for the public tender.
        raw_text: Full text content of the document.
        source_type: Origin type of the document (json/attachment).
    """

    document: Any
    filepath: str
    source_url: str
    title: str
    offer_id: str
    raw_text: str
    source_type: str = "unknown"
